"""added bio and profile pic columns in user

Revision ID: 0523e6fac330
Revises: 3fea8d826e82
Create Date: 2022-03-06 20:58:41.160080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0523e6fac330'
down_revision = '3fea8d826e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
