"""added like and dislike columns

Revision ID: 14aaeec07f8f
Revises: af8c06378f90
Create Date: 2022-03-08 15:23:14.593366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14aaeec07f8f'
down_revision = 'af8c06378f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('dislikes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'likes')
    op.drop_column('pitches', 'dislikes')
    # ### end Alembic commands ###
