"""db update2

Revision ID: 38116090d663
Revises: 14442755a1be
Create Date: 2022-03-07 11:50:32.202706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38116090d663'
down_revision = '14442755a1be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'pitch_id')
    # ### end Alembic commands ###
