"""db update6

Revision ID: 4ae0c55d37ac
Revises: 38e00737566b
Create Date: 2022-03-07 12:15:48.235466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae0c55d37ac'
down_revision = '38e00737566b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
